---
- name: Creating the Ansible user
  hosts: all
  user: root
  tasks:
  - name: Ensure ansible user exists
    user:
      name: ansible
      state: present
      comment: Ansible
  - name: Ensure ansible user accepts the SSH key
    authorized_key:
      user: ansible
      key: https://github.com/maprangzth.keys
      state: present
  - name: Ensure sudo package is installed (RHEL-Base)
    yum:
      name: sudo
      state: present
  - name: Ensure the ansible user is sudoer with no password required
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^ansible ALL\='
      line: 'ansible ALL=(ALL) NOPASSWD:ALL' 
      validate: 'visudo -cf %s'
